## Obtención del grado de confianza en la Policía Preventiva Municipal V2
Pregunta 1.9 del cuestionario principal de la ENSU: ¿Cuánta confianza le inspira la Policía Preventiva Municipal?

### Inicio

In [1]:
import pandas as pd

#### Importar Bases

**Percepción de Inseguridad en la lugares varios** <br>
Fuente: *Encuesta Nacional de Seguridad Pública Urbana 2023 (I Trimestre).* Datos abiertos/2023/Encuesta Nacional de Seguridad Pública Urbana. Trimestre I<br>
Cuestionario principal de la encuesta sección I, II, III, IV (conjunto_de_datos_CB_ENSU_03_2023.csv) <br>
Pregunta *1.9 ¿Cuánta confianza le inspira la Policía Preventiva Municipal?*<br>
https://www.inegi.org.mx/programas/ensu/#Datos_abiertos

In [2]:
# Importar base de Cuestionario principal de la encuesta sección I, II, III, IV
ensu = pd.read_csv('conjunto_de_datos_CB_ENSU_03_2023.csv')
ensu.replace('\r','',inplace=True)
ensu['ID_PER NOM_ENT NOM_MUN NOM_CD TIPO_CUEST DOMINIO REG_CD BP1_9_1'.split()] = ensu['ID_PER NOM_ENT NOM_MUN NOM_CD TIPO_CUEST DOMINIO REG_CD BP1_9_1'.split()].apply(lambda x:x.str.replace('\r',''), axis=1)

#Convertir identificadores de Entidad y Municipio en Texto
ensu['CVE_ENT'] = ensu['CVE_ENT'].astype('str').apply(lambda x:x.zfill(2))
ensu['CVE_MUN'] = ensu['CVE_MUN'].astype('str').apply(lambda x:x.zfill(3))
ensu['ENT_MUN'] = ensu['CVE_ENT'] + ensu['CVE_MUN']
ensu.head()

,ID_VIV,ID_PER,UPM,VIV_SEL,R_SEL,CVE_ENT,NOM_ENT,CVE_MUN,NOM_MUN,LOC,...,BP4_1_2,BP4_1_3,FAC_VIV,FAC_SEL,DOMINIO,EST,UPM_DIS,EST_DIS,REG_CD,ENT_MUN
0,100071.006,0100071.006.01,100071,5,1,01,AGUASCALIENTES,001,AGUASCALIENTES,1,...,5,5,958,1916,U,2,1,142,,01001
1,100071.026,0100071.026.01,100071,1,1,01,AGUASCALIENTES,001,AGUASCALIENTES,1,...,6,5,958,958,U,2,1,142,,01001
2,100071.033,0100071.033.03,100071,2,3,01,AGUASCALIENTES,001,AGUASCALIENTES,1,...,0,0,958,1916,U,2,1,142,,01001
3,100071.115,0100071.115.01,100071,3,1,01,AGUASCALIENTES,001,AGUASCALIENTES,1,...,8,8,958,1916,U,2,1,142,,01001
4,100075.028,0100075.028.02,100075,4,2,01,AGUASCALIENTES,001,AGUASCALIENTES,1,...,7,7,1058,3175,U,3,2,143,,01001

### Filtrar Datos de Interés de ENSU
Diccionario de datos (Metadatos): <br>
https://www.inegi.org.mx/rnm/index.php/catalog/859/data-dictionary/F5?file_name=ENSU_CB_0323 <br>

Primero se tienen que filtrar a los que sí identifican a la Policía Preventiva Municipal <br>
* BP1_7_1	Identificación de la Policía Preventiva Municipal
* BP1_9_1	Percepción del grado de confianza en la Policía Preventiva Municipal

In [3]:
#Filtrar columnas de interés de ENSU
ci = 'CD NOM_CD NOM_ENT BP1_7_1 BP1_9_1 FAC_SEL'.split()
ensuci = ensu[ci]

ensuci['NOM_CD'] = ensuci['NOM_CD'].apply(lambda x:x.title())

#Abreviaturas de Entidades Federativas
ef_abr = {'AGUASCALIENTES':'AGS', 'BAJA CALIFORNIA':'BC', 'BAJA CALIFORNIA SUR':'BCS',
       'CAMPECHE':'CAMP', 'COAHUILA DE ZARAGOZA':'COAH', 'COLIMA':'COL', 'CHIAPAS':'CHIS',
       'CHIHUAHUA':'CHIH', 'CIUDAD DE MEXICO':'CDMX', 'DURANGO':'DGO', 'GUANAJUATO':'GTO',
       'GUERRERO':'GRO', 'HIDALGO':'HGO', 'JALISCO':'JAL', 'MEXICO':'MEX', 'MICHOACAN DE OCAMPO':'MICH',
       'MORELOS':'MOR', 'NAYARIT':'NAY', 'NUEVO LEON':'NL', 'OAXACA':'OAX', 'PUEBLA':'PUE',
       'QUERETARO':'QRO', 'QUINTANA ROO':'QROO', 'SAN LUIS POTOSI':'SLP', 'SINALOA':'SIN',
       'SONORA':'SON', 'TABASCO':'TAB', 'TAMAULIPAS':'TAMPS', 'TLAXCALA':'TLAX',
       'VERACRUZ DE IGNACIO DE LA LLAVE':'VER', 'YUCATAN':'YUC', 'ZACATECAS':'ZAC'}
for ef, abr in ef_abr.items():
    ensuci['NOM_ENT'] = ensuci['NOM_ENT'].replace(ef, abr)

ensuci.loc[ensuci['NOM_CD']=='La Laguna','NOM_ENT'] = 'COAH-DGO'
ensuci.loc[ensuci['NOM_CD']=='Tampico','NOM_ENT'] = 'TAMPS-VER'

ensuci.head()

C:\Users\Arturo\AppData\Local\Temp\ipykernel_4664\1963581375.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ensuci['NOM_CD'] = ensuci['NOM_CD'].apply(lambda x:x.title())
C:\Users\Arturo\AppData\Local\Temp\ipykernel_4664\1963581375.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ensuci['NOM_ENT'] = ensuci['NOM_ENT'].replace(ef, abr)

   CD          NOM_CD NOM_ENT  BP1_7_1 BP1_9_1  FAC_SEL
0   1  Aguascalientes     AGS        1       4     1916
1   1  Aguascalientes     AGS        1       2      958
2   1  Aguascalientes     AGS        1       3     1916
3   1  Aguascalientes     AGS        1       1     1916
4   1  Aguascalientes     AGS        1       9     3175

**Ciudades de Interés** <br>
Ciudades con mayor población (de 18 años o más) de acuerdo con dicho levantamiento excluyendo a CDMX porque no aplica.

In [4]:
#Ciudades con mayor población
#Población por Ciudad
#Filtrar municipios de interés (para trabajar con base de 20 municipios con mayor población excluyendo a CDMX porque no aplica)
ppc = ensuci[ensuci['NOM_ENT']!='CDMX'].groupby(['CD','NOM_CD','NOM_ENT'])['FAC_SEL'].sum().reset_index()
ppc.rename(columns = {'FAC_SEL':'POB'}, inplace=True)
# Crear nombre de ciudad, entidad (NOM_CD_ENT)
ppc['NOM_CD_ENT'] = ppc['NOM_CD'] + ', ' + ppc['NOM_ENT']

#Las 20 Ciudades con mayor población
ciu=ppc[['CD','NOM_CD_ENT','POB']].sort_values(by='POB', ascending=False).head(20)
ciu.drop('POB', axis=1, inplace=True)
ciu

    CD                  NOM_CD_ENT
29  36                 Puebla, PUE
21  27    Ecatepec De Morelos, MEX
52  59            Guadalajara, JAL
2    3                 Tijuana, BC
57  64               Monterrey, NL
15  20                   Leon, GTO
13  14         Ciudad Juarez, CHIH
22  28  Ciudad Nezahualcoyotl, MEX
56  63                Zapopan, JAL
20  26                 Toluca, MEX
45  52                 Merida, YUC
6    7         La Laguna, COAH-DGO
30  37              Queretaro, QRO
32  39        San Luis Potosi, SLP
65  88    Naucalpan De Juarez, MEX
31  38                Cancun, QROO
0    1         Aguascalientes, AGS
60  67               Guadalupe, NL
12  13             Chihuahua, CHIH
5    6              Saltillo, COAH

In [5]:
#Filtrar Ciudades de interés (para trabajar con base de 20 municipios con mayor población)
ensuci = ensuci[ensuci['CD'].isin(ciu['CD'])]
ensuci.drop(['NOM_CD', 'NOM_ENT'],axis=1,inplace=True)
ensuci.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5457 entries, 0 to 23229
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CD       5457 non-null   int64
 1   BP1_7_1  5457 non-null   int64
 2   BP1_9_1  5457 non-null   object
 3   FAC_SEL  5457 non-null   int64
dtypes: int64(3), object(1)
memory usage: 213.2+ KB

#### Filtrar personas que identifican a la polcía preventiva municipal
BP1_7_1	Identificación de la Policía Preventiva Municipal <br>
Opciones de respuestas para pregunta 1.7 *¿Usted identifica a la Policía Preventiva Municipal?* <br>
* Sí -> 1
* No -> 2
* No aplica -> 3
* No sabe / no responde -> 9

In [6]:
# Filtrar personas que identifican a la polcía preventiva municipal
ensuci = ensuci[ensuci['BP1_7_1'] == 1]
ensuci.drop('BP1_7_1', axis=1, inplace=True)

#Convertir variable a numérica
ensuci['BP1_9_1'] = ensuci['BP1_9_1'].astype('int')

ensuci.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4264 entries, 0 to 23229
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CD       4264 non-null   int64
 1   BP1_9_1  4264 non-null   int32
 2   FAC_SEL  4264 non-null   int64
dtypes: int32(1), int64(2)
memory usage: 116.6 KB

### Obtención de Porcentaje de Confianza en Policías

Opciones de respuestas para pregunta *1.9 ¿Cuánta confianza le inspira la Policía Preventiva Municipal?* 

* Mucha confianza -> 1
* Algo de confianza -> 2
* Algo de desconfianza -> 3
* Mucha desconfianza -> 4
* No sabe / no responde -> 9

#### Colapsar datos por municipio

In [7]:
#Población por Municipio
ppm = ensuci.groupby('CD')['FAC_SEL'].sum().reset_index()
ppm.rename(columns = {'FAC_SEL':'POB'}, inplace=True)

#Población que considera efectiva a la policía
# 1 -> Mucha confianza
# 2 -> Algo de confianza
pef = ensuci[(ensuci['BP1_9_1'] == 1) | (ensuci['BP1_9_1'] == 2)]. groupby('CD')['FAC_SEL'].sum().reset_index()
pef.rename(columns = {'FAC_SEL':'CONF'}, inplace=True)

#Unión de variables
union = ppm.merge(pef, how='left', on='CD')

#Porcentaje de efectividad de policías
union['PCT_CONF'] = union['CONF']/union['POB']

#Variable de interés (porcentaje que se siente inseguro) en Data Frame
var_df=union[['CD','PCT_CONF']]

var_df.head()

   CD  PCT_CONF
0   1  0.594760
1   3  0.258088
2   6  0.707409
3   7  0.437661
4  13  0.568104

### Unir Base de Efectividad de Policías con Nombres de Estados y Municipios

In [8]:
#Base de Efectividad por Municipios
conf_poli = ciu.merge(var_df, how='left', on='CD')
conf_poli

    CD                  NOM_CD_ENT  PCT_CONF
0   36                 Puebla, PUE  0.456959
1   27    Ecatepec De Morelos, MEX  0.401259
2   59            Guadalajara, JAL  0.428000
3    3                 Tijuana, BC  0.258088
4   64               Monterrey, NL  0.564954
5   20                   Leon, GTO  0.465512
6   14         Ciudad Juarez, CHIH  0.385191
7   28  Ciudad Nezahualcoyotl, MEX  0.703744
8   63                Zapopan, JAL  0.588042
9   26                 Toluca, MEX  0.390844
10  52                 Merida, YUC  0.659942
11   7         La Laguna, COAH-DGO  0.437661
12  37              Queretaro, QRO  0.630504
13  39        San Luis Potosi, SLP  0.454356
14  88    Naucalpan De Juarez, MEX  0.384871
15  38                Cancun, QROO  0.332714
16   1         Aguascalientes, AGS  0.594760
17  67               Guadalupe, NL  0.660326
18  13             Chihuahua, CHIH  0.568104
19   6              Saltillo, COAH  0.707409

#### Cifras Nacionales

In [9]:
# Porcentaje Nacional
nac_pob = ensu['FAC_SEL'].sum() #total población de la encuesta
nac_pob_iap = ensu[ensu['BP1_7_1'] == 1]['FAC_SEL'].sum() #total población de la encuesta que identifica a la policía
nac_conf = ensu[(ensu['BP1_9_1'] == '1') | (ensu['BP1_9_1'] == '2')]['FAC_SEL'].sum()
nac_conf_pct = nac_conf/nac_pob_iap

conf_poli.loc[20] = [0, 'Nacional'] + [nac_conf_pct]
conf_poli

    CD                  NOM_CD_ENT  PCT_CONF
0   36                 Puebla, PUE  0.456959
1   27    Ecatepec De Morelos, MEX  0.401259
2   59            Guadalajara, JAL  0.428000
3    3                 Tijuana, BC  0.258088
4   64               Monterrey, NL  0.564954
5   20                   Leon, GTO  0.465512
6   14         Ciudad Juarez, CHIH  0.385191
7   28  Ciudad Nezahualcoyotl, MEX  0.703744
8   63                Zapopan, JAL  0.588042
9   26                 Toluca, MEX  0.390844
10  52                 Merida, YUC  0.659942
11   7         La Laguna, COAH-DGO  0.437661
12  37              Queretaro, QRO  0.630504
13  39        San Luis Potosi, SLP  0.454356
14  88    Naucalpan De Juarez, MEX  0.384871
15  38                Cancun, QROO  0.332714
16   1         Aguascalientes, AGS  0.594760
17  67               Guadalupe, NL  0.660326
18  13             Chihuahua, CHIH  0.568104
19   6              Saltillo, COAH  0.707409
20   0                    Nacional  0.499438

In [12]:
#Organizar Tabla a Exportar a Excel
conf_poli = conf_poli.sort_values(by='PCT_CONF')
conf_poli

    CD                  NOM_CD_ENT  PCT_CONF
3    3                 Tijuana, BC  0.258088
15  38                Cancun, QROO  0.332714
14  88    Naucalpan De Juarez, MEX  0.384871
6   14         Ciudad Juarez, CHIH  0.385191
9   26                 Toluca, MEX  0.390844
1   27    Ecatepec De Morelos, MEX  0.401259
2   59            Guadalajara, JAL  0.428000
11   7         La Laguna, COAH-DGO  0.437661
13  39        San Luis Potosi, SLP  0.454356
0   36                 Puebla, PUE  0.456959
5   20                   Leon, GTO  0.465512
20   0                    Nacional  0.499438
4   64               Monterrey, NL  0.564954
18  13             Chihuahua, CHIH  0.568104
8   63                Zapopan, JAL  0.588042
16   1         Aguascalientes, AGS  0.594760
12  37              Queretaro, QRO  0.630504
10  52                 Merida, YUC  0.659942
17  67               Guadalupe, NL  0.660326
7   28  Ciudad Nezahualcoyotl, MEX  0.703744
19   6              Saltillo, COAH  0.707409

#### Tabla 1: Porcentaje de la población de 18 años que identificó a la Policía Preventiva Municipal como una autoridad que le inspira confianza de las 20 ciudades con más población

In [13]:
conf_poli.to_excel('Confianza en Policía Municipal V2.xlsx', index=False)